### PR TITLE
Add Thirdweb Tutorial

### PR DESCRIPTION
**Pull request by 0xiliyan**
What 💻
Thirdweb is a development platform that offers pre-built smart contracts and tools, enabling developers to easily build, deploy, and manage web3 applications across various blockchains. It is really popular among many developers and people with limited or no coding skills, this is why the idea came up to create this simple onboarding tutorial.

Why ✋
It may be hard to navigate the Thirdweb documentation yourself with zkSync in particular and creating a signer object, which are basic and essential steps if you want to use the SDK, hence those are outlined in the guide. In addition a simple flow to deploy NFT contract and mint and NFT instance is included as code snippets.

### CODE REVIEW

**Comment by 0xiliyan** [comment]
Something I noticed is that I'm using couple different git user.name when committing (its my work laptop and I switched it to new one as well). The contributor is only one and its me - 0xiliyan.

**Review by dutterbutter — COMMENTED** [review]
@0xiliyan can you confirm this tutorial works as expected? Do you have tx link you could share after going through it?

**Comment by 0xiliyan** [comment]
> @0xiliyan can you confirm this tutorial works as expected? Do you have tx link you could share after going through it?

@dutterbutter I was able to deploy and test the tutorial in the past but it looks like this typescript SDK repository is not well maintained and they have issues with the NFT contracts in particular as I read across forums, kept getting errors this time after I updated the repo. So instead I decided it would be better to write a guide for using the React SDK which I've used a couple of times already and its working perfectly!

Here is an NFT claim transaction, I just deployed and NFT Drop contract and followed the tutorial exactly to utilize the React SDK in order to connect to the contract and claim an NFT: 

https://sepolia.explorer.zksync.io/tx/0x4c414c50e53aa36ac71046269388f5439da42858f173f5ed2a670d8110fb8413

**Comment by itsacoyote** [comment]
Thank you for your contribution!

We wanted to let you know that this repository will be archived shortly as we've moved our work to a new repository. If you would still like to contribute, please feel free to submit your changes to our new repo: https://github.com/matter-labs/zksync-docs. We also have a new repo for community contributed guides and tutorials at https://github.com/zkSync-Community-Hub/community-code

We appreciate your understanding and hope to see your contributions in the new repo!

**Pull request closed without merging**
